//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belikov_IA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaning_Rooms
    {
        public int id { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<System.DateTime> cleaningTime { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string cleaningStatus { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
