//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belikov_IA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaning_Rooms
    {
        public int id { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<System.DateTime> cleaningTime { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string cleaningStatus { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
