//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belikov_IA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public Nullable<int> reservation_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> quality { get; set; }
        public string status { get; set; }
    
        public virtual C_Services C_Services { get; set; }
    }
}
