//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belikov_IA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayDay
    {
        public int id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public Nullable<int> reservation_id { get; set; }
        public string paymentMethod { get; set; }
        public Nullable<bool> IsPayed { get; set; }
        public string price { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual Reservations Reservations { get; set; }
    }
}
