//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belikov_IA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayDay
    {
        public int id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public Nullable<int> reservation_id { get; set; }
        public string paymentMethod { get; set; }
        public Nullable<bool> IsPayed { get; set; }
        public string price { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual Reservations Reservations { get; set; }
    }
}
