//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belikov_IA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservations()
        {
            this.PayDay = new HashSet<PayDay>();
        }
    
        public int id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<System.DateTime> checkIn { get; set; }
        public Nullable<System.DateTime> checkOut { get; set; }
        public string status { get; set; }
    
        public virtual Guests Guests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayDay> PayDay { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
