//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belikov_IA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Cleaning_Rooms = new HashSet<Cleaning_Rooms>();
        }
    
        public int id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string UserName { get; set; }
        public string Passwor { get; set; }
        public string role { get; set; }
        public Nullable<bool> TryPlugin { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public Nullable<bool> IsFirst { get; set; }
        public Nullable<System.DateTime> lastLogin { get; set; }
        public Nullable<int> FailedLoginAttempts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cleaning_Rooms> Cleaning_Rooms { get; set; }
    }
}
